# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
development:
  adapter: postgresql
  host: localhost
  database: dan
  encoding: UTF8

test:
  adapter: postgresql
  host: localhost
  database: dan        # or whatever the name is
  encoding: UTF8

production:
  adapter: postgresql
  database: dan
  encoding: UTF8
